import React, { useEffect, useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { Building2, ChevronDown, KeyRound, LogOut, Plus, Search, ShieldCheck, Star, Store, Users, X } from 'lucide-react';
import './styles.css';

queueMicrotask(() => createRoot(document.getElementById('root')).render(<App/>));

function Dashboard({ title, subtitle, actions, children }) { return <main className="dashboard"><div className="page-title"><div><span className="eyebrow">StoreRate platform</span><h1>{title}</h1><p>{subtitle}</p></div>{actions && <div className="actions">{actions}</div>}</div>{children}</main> }
function Metric({ icon, label, value }) { return <article className="metric"><span className="metric-icon">{icon}</span><div><p>{label}</p><strong>{value ?? '—'}</strong></div></article> }
function Empty({ text }) { return <div className="empty"><Store size={25}/><p>{text}</p></div> }
function Filters({ filters, setFilters }) { return <div className="filters">{['name','email','address'].map(field=><input key={field} value={filters[field]} onChange={e=>setFilters({...filters,[field]:e.target.value})} placeholder={`Filter by ${field}`}/>)}<select value={filters.role} onChange={e=>setFilters({...filters,role:e.target.value})}><option value="">All roles</option><option value="USER">Customers</option><option value="OWNER">Store owners</option><option value="ADMIN">Administrators</option></select></div> }
function CreateModal({ type, session, close, saved }) { const [form,setForm]=useState({name:'',email:'',address:'',password:'',role:'USER',ownerId:''}); const [errors,setErrors]=useState({}); const [owners,setOwners]=useState([]); useEffect(()=>{if(type==='store') request('/admin/users?role=OWNER',{token:session.token}).then(setOwners);},[]); const update=e=>setForm({...form,[e.target.name]:e.target.value}); async function submit(e){e.preventDefault();setErrors({});try{await request(type==='user'?'/admin/users':'/admin/stores',{token:session.token,method:'POST',body:JSON.stringify(form)});saved();}catch(err){setErrors(err.errors||{form:err.message});}} return <Modal title={type==='user'?'Add a user':'Add a store'} close={close}><form onSubmit={submit}>{type==='user'&&<><Field label="Full name" name="name" value={form.name} onChange={update} error={errors.name} placeholder="20 to 60 characters"/><label className="field"><span>Role</span><select name="role" value={form.role} onChange={update}><option value="USER">Customer</option><option value="OWNER">Store owner</option><option value="ADMIN">Administrator</option></select></label></>}<Field label={type==='user'?'Email address':'Store email'} name="email" type="email" value={form.email} onChange={update} error={errors.email}/><Field label="Address" name="address" value={form.address} onChange={update} error={errors.address}/>{type==='user'&&<><Field label="Temporary password" name="password" type="password" value={form.password} onChange={update} error={errors.password}/><p className="help">{passwordHint}</p></>}{type==='store'&&<><Field label="Store name" name="name" value={form.name} onChange={update}/><label className="field"><span>Store owner (optional)</span><select name="ownerId" value={form.ownerId} onChange={update}><option value="">Assign later</option>{owners.map(o=><option value={o.id} key={o.id}>{o.name}</option>)}</select></label></>}{errors.form&&<p className="form-error">{errors.form}</p>}<div className="modal-actions"><button type="button" className="secondary" onClick={close}>Cancel</button><button className="primary">Create {type}</button></div></form></Modal> }
function PasswordModal({ session, close, flash }) { const [password,setPassword]=useState('');const [error,setError]=useState('');async function submit(e){e.preventDefault();try{const r=await request('/auth/password',{token:session.token,method:'PATCH',body:JSON.stringify({password})});flash(r.message);close();}catch(e){setError(e.errors?.password||e.message);}}return <Modal title="Change password" close={close}><form onSubmit={submit}><Field label="New password" type="password" value={password} onChange={e=>setPassword(e.target.value)} error={error}/><p className="help">{passwordHint}</p><div className="modal-actions"><button type="button" className="secondary" onClick={close}>Cancel</button><button className="primary">Save password</button></div></form></Modal>}
function App(){const [session,setSession]=useState(stored);const [toast,setToast]=useState('');const [password,setPassword]=useState(false);const flash=message=>setToast(message||'Action completed.');const logout=()=>{localStorage.removeItem('store-rate-session');setSession(null);};if(!session)return <><Auth setSession={setSession}/><Toast message={toast} clear={()=>setToast('')}/></>;const view=session.user.role==='ADMIN'?<Admin session={session} flash={flash}/>:session.user.role==='OWNER'?<Owner session={session} flash={flash}/>:<Customer session={session} flash={flash}/>;return <><Header session={session} logout={logout} setPassword={setPassword}/>{view}{password&&<PasswordModal session={session} close={()=>setPassword(false)} flash={flash}/>}<Toast message={toast} clear={()=>setToast('')}/></>}

const API = import.meta.env.VITE_API_URL || 'http://localhost:4000/api';
const stored = JSON.parse(localStorage.getItem('store-rate-session') || 'null');
async function request(path, { token, ...options } = {}) { const response = await fetch(API + path, { ...options, headers: { 'Content-Type': 'application/json', ...(token ? { Authorization: `Bearer ${token}` } : {}), ...options.headers } }); const data = await response.json().catch(() => ({})); if (!response.ok) throw data; return data; }
const passwordHint = '8–16 characters, with an uppercase letter and a special character.';
function Stars({ value = 0, interactive, onChange }) { return <span className={'stars ' + (interactive ? 'interactive' : '')}>{[1,2,3,4,5].map(n => <button key={n} type="button" aria-label={`${n} stars`} disabled={!interactive} onClick={() => onChange(n)} className={n <= Math.round(value) ? 'filled' : ''}><Star size={18} fill="currentColor" /></button>)}</span> }
function Toast({ message, clear }) { useEffect(() => { const id = setTimeout(clear, 4000); return () => clearTimeout(id); }, [message]); return message ? <div className="toast">{message}<button onClick={clear}><X size={16}/></button></div> : null; }
function Field({ label, error, ...props }) { return <label className="field"><span>{label}</span><input {...props}/>{error && <small>{error}</small>}</label> }
function Modal({ title, children, close }) { return <div className="modal-backdrop" role="presentation"><section className="modal" role="dialog" aria-modal="true"><div className="modal-head"><h2>{title}</h2><button className="icon-button" onClick={close}><X/></button></div>{children}</section></div> }
function Auth({ setSession }) {
  const [mode, setMode] = useState('login'); const [form, setForm] = useState({ name: '', email: '', address: '', password: '' }); const [errors, setErrors] = useState({}); const [loading, setLoading] = useState(false);
  const update = e => setForm({ ...form, [e.target.name]: e.target.value });
  async function submit(e) { e.preventDefault(); setLoading(true); setErrors({}); try { const path = mode === 'login' ? '/auth/login' : '/auth/signup'; const body = mode === 'login' ? { email: form.email, password: form.password } : form; const session = await request(path, { method: 'POST', body: JSON.stringify(body) }); localStorage.setItem('store-rate-session', JSON.stringify(session)); setSession(session); } catch (error) { setErrors(error.errors || { form: error.message || 'Unable to continue. Please try again.' }); } finally { setLoading(false); } }
  return <main className="auth-page"><div className="auth-intro"><div className="brand"><span className="brand-mark"><Store size={22}/></span>StoreRate</div><div><span className="eyebrow">Feedback made simple</span><h1>Better store experiences start with a clear signal.</h1><p>Discover local stores, share your experience, and help great businesses grow.</p></div><div className="trust-row"><span><ShieldCheck/> Secure role-based access</span><span><Star/> Honest 1–5 ratings</span></div></div><section className="auth-card"><div className="segmented"><button className={mode === 'login' ? 'selected' : ''} onClick={() => setMode('login')}>Sign in</button><button className={mode === 'signup' ? 'selected' : ''} onClick={() => setMode('signup')}>Create account</button></div><h2>{mode === 'login' ? 'Welcome back' : 'Join StoreRate'}</h2><p className="muted">{mode === 'login' ? 'Sign in to continue to your dashboard.' : 'Create a customer account in a few moments.'}</p><form onSubmit={submit}>{mode === 'signup' && <><Field label="Full name" name="name" value={form.name} onChange={update} placeholder="At least 20 characters" error={errors.name}/><Field label="Address" name="address" value={form.address} onChange={update} placeholder="Your full address" error={errors.address}/></>}<Field label="Email address" name="email" type="email" value={form.email} onChange={update} placeholder="you@example.com" error={errors.email}/><Field label="Password" name="password" type="password" value={form.password} onChange={update} placeholder="••••••••" error={errors.password}/>{mode === 'signup' && <p className="help">{passwordHint}</p>}{errors.form && <p className="form-error">{errors.form}</p>}<button className="primary full" disabled={loading}>{loading ? 'Please wait…' : mode === 'login' ? 'Sign in' : 'Create account'}</button></form><p className="switcher">{mode === 'login' ? 'New to StoreRate?' : 'Already have an account?'} <button onClick={() => setMode(mode === 'login' ? 'signup' : 'login')}>{mode === 'login' ? 'Create one' : 'Sign in'}</button></p></section></main>
}
function Header({ session, logout, setPassword }) { const [open, setOpen] = useState(false); const initials = session.user.name.split(' ').map(x=>x[0]).slice(0,2).join(''); return <header><div className="brand"><span className="brand-mark"><Store size={20}/></span><span className="brand-name">StoreRate</span></div><div className="profile"><button className="profile-button" onClick={() => setOpen(!open)}><span className="avatar">{initials}</span><span className="profile-copy"><strong title={session.user.name}>{session.user.name}</strong><small>{session.user.role === 'USER' ? 'Customer' : session.user.role === 'OWNER' ? 'Store owner' : 'Administrator'}</small></span><ChevronDown className="profile-chevron" size={16}/></button>{open && <div className="profile-menu"><button onClick={() => { setPassword(true); setOpen(false); }}><KeyRound size={16}/> Change password</button><button onClick={logout}><LogOut size={16}/> Sign out</button></div>}</div></header> }
function SortHead({ label, field, sort, setSort }) { const active = sort.field === field; return <th><button className="sort" onClick={() => setSort({ field, order: active && sort.order === 'ASC' ? 'DESC' : 'ASC' })}>{label}{active && <span>{sort.order === 'ASC' ? '↑' : '↓'}</span>}</button></th> }
function Customer({ session, flash }) { const [stores, setStores] = useState([]); const [search, setSearch] = useState(''); const [sort, setSort] = useState({ field: 'name', order: 'ASC' }); const [pending, setPending] = useState({});
  const load = async () => { try { setStores(await request(`/stores?search=${encodeURIComponent(search)}&sort=${sort.field}&order=${sort.order}`, { token: session.token })); } catch (e) { flash(e.message); } }; useEffect(() => { const id = setTimeout(load, 250); return () => clearTimeout(id); }, [search, sort]);
  async function rate(id, value) { setPending({ ...pending, [id]: true }); try { await request(`/stores/${id}/rating`, { token: session.token, method: 'PUT', body: JSON.stringify({ value }) }); flash('Your rating has been saved.'); load(); } catch (e) { flash(e.message); } finally { setPending({ ...pending, [id]: false }); } }
  return <Dashboard title="Find a store" subtitle="Browse registered stores and share a rating based on your experience."><div className="toolbar"><div className="search"><Search size={19}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search by store name or address"/></div><span className="result-count">{stores.length} stores</span></div><div className="store-grid">{stores.map(store => <article className="store-card" key={store.id}><div className="store-icon"><Building2 size={22}/></div><div className="store-card-head"><h3>{store.name}</h3><p>{store.address}</p></div><div className="rating-line"><span>Overall rating</span><strong>{store.averageRating ? store.averageRating.toFixed(1) : 'New'}</strong><Stars value={store.averageRating}/></div><div className="divider"/><div className="my-rating"><span>Your rating</span><Stars value={store.myRating || 0} interactive onChange={n => rate(store.id, n)}/><em>{pending[store.id] ? 'Saving…' : store.myRating ? `${store.myRating} of 5` : 'Choose 1–5 stars'}</em></div></article>)}</div>{!stores.length && <Empty text="No stores match your search."/>}</Dashboard> }
function Admin({ session, flash }) { const [tab, setTab] = useState('overview'); const [summary, setSummary] = useState({}); const [users, setUsers] = useState([]); const [stores, setStores] = useState([]); const [modal, setModal] = useState(null); const [detail, setDetail] = useState(null); const [filters, setFilters] = useState({ name:'', email:'', address:'', role:'' }); const [sort, setSort] = useState({ field:'name', order:'ASC' });
  const load = async () => { try { const [s,u,st] = await Promise.all([request('/admin/summary',{token:session.token}), request(`/admin/users?${new URLSearchParams({...filters,sort:sort.field,order:sort.order})}`,{token:session.token}),request(`/stores?sort=${sort.field}&order=${sort.order}`,{token:session.token})]); setSummary(s); setUsers(u); setStores(st); } catch(e) { flash(e.message); } }; useEffect(()=>{load();},[filters,sort]);
  const showDetail = async id => { try { setDetail(await request(`/admin/users/${id}`, {token:session.token})); } catch(e){flash(e.message);} };
  return <Dashboard title="Admin workspace" subtitle="Manage platform activity, people, and the stores they rate." actions={<><button className="secondary" onClick={()=>setModal('user')}><Plus size={17}/> Add user</button><button className="primary" onClick={()=>setModal('store')}><Plus size={17}/> Add store</button></>}><nav className="tabs">{[['overview','Overview'],['users','Users'],['stores','Stores']].map(([key,label])=><button key={key} className={tab===key?'active':''} onClick={()=>setTab(key)}>{label}</button>)}</nav>{tab==='overview' && <><div className="metrics"><Metric icon={<Users/>} label="Total users" value={summary.users}/><Metric icon={<Store/>} label="Registered stores" value={summary.stores}/><Metric icon={<Star/>} label="Submitted ratings" value={summary.ratings}/></div><section className="panel"><h2>At a glance</h2><p className="muted">Use the tabs above to create, filter, sort, and inspect users and stores.</p></section></>}{tab==='users' && <><Filters filters={filters} setFilters={setFilters}/><section className="panel table-panel"><table><thead><tr><SortHead label="Name" field="name" sort={sort} setSort={setSort}/><SortHead label="Email" field="email" sort={sort} setSort={setSort}/><SortHead label="Address" field="address" sort={sort} setSort={setSort}/><SortHead label="Role" field="role" sort={sort} setSort={setSort}/><th></th></tr></thead><tbody>{users.map(u=><tr key={u.id}><td>{u.name}</td><td>{u.email}</td><td>{u.address}</td><td><span className={'badge '+u.role.toLowerCase()}>{u.role}</span></td><td><button className="link" onClick={()=>showDetail(u.id)}>View</button></td></tr>)}</tbody></table>{!users.length&&<Empty text="No users match these filters."/>}</section></>}{tab==='stores' && <section className="panel table-panel"><table><thead><tr><SortHead label="Store" field="name" sort={sort} setSort={setSort}/><SortHead label="Email" field="email" sort={sort} setSort={setSort}/><SortHead label="Address" field="address" sort={sort} setSort={setSort}/><th>Rating</th></tr></thead><tbody>{stores.map(s=><tr key={s.id}><td>{s.name}</td><td>{s.email}</td><td>{s.address}</td><td><strong>{s.averageRating ? s.averageRating.toFixed(1) : '—'}</strong></td></tr>)}</tbody></table></section>}{modal && <CreateModal type={modal} session={session} close={()=>setModal(null)} saved={()=>{setModal(null);flash(`${modal==='user'?'User':'Store'} created successfully.`);load();}}/>}{detail&&<Modal title="User details" close={()=>setDetail(null)}><div className="detail-list"><p><span>Name</span>{detail.name}</p><p><span>Email</span>{detail.email}</p><p><span>Address</span>{detail.address}</p><p><span>Role</span><b>{detail.role}</b></p>{detail.role==='OWNER'&&<p><span>Store rating</span>{detail.rating?.toFixed(1)||'—'}</p>}</div></Modal>}</Dashboard> }
function Owner({ session, flash }) { const [data,setData]=useState({stores:[],ratings:[],averageRating:0}); useEffect(()=>{request('/owner/dashboard',{token:session.token}).then(setData).catch(e=>flash(e.message));},[]); return <Dashboard title="Store performance" subtitle="See how customers are rating your store and who shared feedback."><div className="metrics"><Metric icon={<Store/>} label="Your stores" value={data.stores.length}/><Metric icon={<Star/>} label="Average rating" value={data.averageRating ? data.averageRating.toFixed(1) : '—'}/><Metric icon={<Users/>} label="Ratings received" value={data.ratings.length}/></div><section className="panel table-panel"><div className="panel-title"><div><h2>Recent customer feedback</h2><p className="muted">Customers who submitted a rating for your store.</p></div></div><table><thead><tr><th>Customer</th><th>Email</th><th>Store</th><th>Rating</th><th>Submitted</th></tr></thead><tbody>{data.ratings.map(r=><tr key={r.id}><td>{r.User.name}</td><td>{r.User.email}</td><td>{r.Store.name}</td><td><span className="inline-rating"><b>{r.value}</b><Star size={15} fill="currentColor"/></span></td><td>{new Date(r.createdAt).toLocaleDateString()}</td></tr>)}</tbody></table>{!data.ratings.length&&<Empty text="No customer ratings yet. Feedback will appear here when customers rate your store."/>}</section></Dashboard> }
